#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# dsplays 17 and then bad luck from Italy for the 17th loop iteration

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done